-- Append-only event log (FR-05). One row per event; state is folded in application code.
-- account_id is denormalised onto every row so Unity Catalog row filters can key on it (003_row_filters.sql).
CREATE TABLE IF NOT EXISTS ${catalog}.${schema}.submission_event (
  submission_id STRING    NOT NULL COMMENT 'UUIDv7 generated by the app',
  account_id    STRING    NOT NULL COMMENT 'Payer / sold-to; identical on every event of a submission',
  seq           INT       NOT NULL COMMENT '1-based, gapless per submission',
  event_type    STRING    NOT NULL COMMENT 'See docs/data_contract.md',
  actor         STRING    NOT NULL,
  actor_role    STRING    NOT NULL COMMENT 'CUSTOMER | INTERNAL | SYSTEM',
  occurred_at   TIMESTAMP NOT NULL,
  payload       STRING    NOT NULL COMMENT 'JSON; shape per event_type',
  ingested_at   TIMESTAMP NOT NULL
)
USING DELTA
CLUSTER BY (account_id, submission_id)
TBLPROPERTIES (
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true',
  'delta.deletedFileRetentionDuration' = 'interval 30 days'
);
